version: "3.6"

services:
  front:
    build:
      context: .
      dockerfile: local.dockerfile
    container_name: front
    ports:
      - "3000:3000"
      - "49153:49153"
    volumes:
      - ".:/app"

networks:
  vs-network:
    name: vs-network
    driver: bridge